services:
  session:
    build: .
    ports:
      - "6379:6379"
    networks:
      - superforum-backend
  db:
    image: postgres
    restart: always
    shm_size: 128m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ../super-forum-server/.env:/var/.env
      - ./data/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - superforum-backend

networks:
  superforum-backend:
    driver: bridge

